In [ ]:
-1/10*()

In [1]:
from math import log2

In [2]:
-(1/2)*log2(1/10)

1.660964047443681

In [3]:
-((3/4)*log2(3/4)+ (1/4)*log2(1/4))

0.8112781244591328

In [4]:
1-0.8112781244591328

0.18872187554086717

In [5]:
log2(0.75)

-0.4150374992788438

In [6]:
log2(0.25)

-2.0

In [8]:
-((9/10)*log2(9/10)+(1/10)*log2(1/10))

0.4689955935892812

In [9]:
from sklearn.tree import DecisionTreeRegressor

In [10]:
dt=DecisionTreeRegressor()

In [11]:
(725+302)/(725+302+158+75)

0.8150793650793651

In [13]:
302/(302+158)

0.6565217391304348

In [323]:
import pandas as pd

In [376]:
train=pd.read_csv('C://Users//vansh//Downloads//train (3).csv')

In [377]:
test=pd.read_csv('C://Users//vansh//Downloads//test (3).csv')

In [378]:
train.head()

   Year  Month ProductCategory  Sales(In ThousandDollars)
0  2009      1   WomenClothing                     1755.0
1  2009      1     MenClothing                      524.0
2  2009      1   OtherClothing                      936.0
3  2009      2   WomenClothing                     1729.0
4  2009      2     MenClothing                      496.0

In [379]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 4 columns):
Year                         216 non-null int64
Month                        216 non-null int64
ProductCategory              216 non-null object
Sales(In ThousandDollars)    204 non-null float64
dtypes: float64(1), int64(2), object(1)
memory usage: 6.8+ KB

In [380]:
macro=pd.read_excel('C://Users//vansh//Downloads//macro_economic.xlsx')

In [381]:
test.head()

   Year  Month ProductCategory  Sales(In ThousandDollars)
0  2015      1   WomenClothing                        NaN
1  2015      1     MenClothing                        NaN
2  2015      1   OtherClothing                        NaN
3  2015      2   WomenClothing                        NaN
4  2015      2     MenClothing                        NaN

In [382]:
train.Month.replace(to_replace=[1,2,3,4,5,6,7,8,9,10,11,12],value=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct',
                                                                  'Nov','Dec'],inplace=True)

In [383]:
test.Month.replace(to_replace=[1,2,3,4,5,6,7,8,9,10,11,12],value=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct',
                                                                  'Nov','Dec'],inplace=True)

In [384]:
test.head()

   Year Month ProductCategory  Sales(In ThousandDollars)
0  2015   Jan   WomenClothing                        NaN
1  2015   Jan     MenClothing                        NaN
2  2015   Jan   OtherClothing                        NaN
3  2015   Feb   WomenClothing                        NaN
4  2015   Feb     MenClothing                        NaN

In [385]:
train['Year-Month']=train['Year'].map(str)+' - ' + train['Month']

In [386]:
train['Year-Month']

0      2009 - Jan
1      2009 - Jan
2      2009 - Jan
3      2009 - Feb
4      2009 - Feb
5      2009 - Feb
6      2009 - Mar
7      2009 - Mar
8      2009 - Mar
9      2009 - Apr
10     2009 - Apr
11     2009 - Apr
12     2009 - May
13     2009 - May
14     2009 - May
15     2009 - Jun
16     2009 - Jun
17     2009 - Jun
18     2009 - Jul
19     2009 - Jul
20     2009 - Jul
21     2009 - Aug
22     2009 - Aug
23     2009 - Aug
24     2009 - Sep
25     2009 - Sep
26     2009 - Sep
27     2009 - Oct
28     2009 - Oct
29     2009 - Oct
          ...
186    2014 - Mar
187    2014 - Mar
188    2014 - Mar
189    2014 - Apr
190    2014 - Apr
191    2014 - Apr
192    2014 - May
193    2014 - May
194    2014 - May
195    2014 - Jun
196    2014 - Jun
197    2014 - Jun
198    2014 - Jul
199    2014 - Jul
200    2014 - Jul
201    2014 - Aug
202    2014 - Aug
203    2014 - Aug
204    2014 - Sep
205    2014 - Sep
206    2014 - Sep
207    2014 - Oct
208    2014 - Oct
209    2014 - Oct
210    2014 - Nov
211    2014 - Nov
212    2014 - Nov
213    2014 - Dec
214    2014 - Dec
215    2014 - Dec
Name: Year-Month, Length: 216, dtype: object

In [387]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
Year                         216 non-null int64
Month                        216 non-null object
ProductCategory              216 non-null object
Sales(In ThousandDollars)    204 non-null float64
Year-Month                   216 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 8.5+ KB

In [388]:
train.ProductCategory.value_counts()

MenClothing      72
WomenClothing    72
OtherClothing    72
Name: ProductCategory, dtype: int64

In [389]:
train[(train.ProductCategory=='WomenClothing')].mean()

Year                         2011.500000
Sales(In ThousandDollars)    3293.478261
dtype: float64

In [390]:
)

SyntaxError: invalid syntax (<ipython-input-390-a35077a93b18>, line 1)

In [391]:
train[train['ProductCategory']=='WomenClothing']['Sales(In ThousandDollars)'].fillna(value=3293,inplace=True)

C:\Users\vansh\Anaconda4\lib\site-packages\pandas\core\generic.py:5434: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [392]:
train[(train.ProductCategory=='MenClothing')].mean()

Year                         2011.500000
Sales(In ThousandDollars)     673.808824
dtype: float64

In [393]:
train[train['ProductCategory']=='MenClothing']['Sales(In ThousandDollars)'].fillna(value=674,inplace=True)

In [394]:
train[(train.ProductCategory=='OtherClothing')].mean()

Year                         2011.500000
Sales(In ThousandDollars)    1107.626866
dtype: float64

In [395]:
train[train['ProductCategory']=='OtherClothing']['Sales(In ThousandDollars)'].fillna(value=1008,inplace=True)

In [396]:
train['Sales(In ThousandDollars)'].median()

1080.5

In [397]:
train.fillna(value=1080,inplace=True)

In [398]:
test['Year-Month']=test['Year'].map(str)+' - ' + test['Month']

In [399]:
test['Year-Month']

0     2015 - Jan
1     2015 - Jan
2     2015 - Jan
3     2015 - Feb
4     2015 - Feb
5     2015 - Feb
6     2015 - Mar
7     2015 - Mar
8     2015 - Mar
9     2015 - Apr
10    2015 - Apr
11    2015 - Apr
12    2015 - May
13    2015 - May
14    2015 - May
15    2015 - Jun
16    2015 - Jun
17    2015 - Jun
18    2015 - Jul
19    2015 - Jul
20    2015 - Jul
21    2015 - Aug
22    2015 - Aug
23    2015 - Aug
24    2015 - Sep
25    2015 - Sep
26    2015 - Sep
27    2015 - Oct
28    2015 - Oct
29    2015 - Oct
30    2015 - Nov
31    2015 - Nov
32    2015 - Nov
33    2015 - Dec
34    2015 - Dec
35    2015 - Dec
Name: Year-Month, dtype: object

In [400]:
macro.head()

,Year-Month,Monthly Nominal GDP Index (inMillion$),Monthly Real GDP Index (inMillion$),CPI,PartyInPower,unemployment rate,CommercialBankInterestRateonCreditCardPlans,"Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan",Earnings or wages in dollars per hour,AdvertisingExpenses (in Thousand Dollars),Cotton Monthly Price - US cents per Pound(lbs),Change(in%),Average upland planted(million acres),Average upland harvested(million acres),yieldperharvested acre,Production (in 480-lb netweright in million bales),Mill use (in 480-lb netweright in million bales),Exports
0,2009 - Jan,14421.752895,14407.053343,233.402,Democrats,7.8,12.03,11.44,22.05,137,57.70,4.02,9.296,7.559,799,12.589,4.17,11.550
1,2009 - Feb,14389.200466,14366.176571,234.663,Democrats,8.3,12.97,11.05,22.22,200,55.21,-4.32,9.296,7.559,799,12.589,3.87,11.100
2,2009 - Mar,14340.701639,14351.786822,235.067,Democrats,8.7,12.97,11.05,22.22,?,51.50,-6.72,9.296,7.559,799,12.589,3.72,11.650
3,2009 - Apr,14326.815525,14351.601731,235.582,Democrats,9.0,12.97,11.05,22.13,214,56.78,10.25,9.296,7.559,787,12.400,3.62,12.225
4,2009 - May,14345.904809,14368.123959,235.975,Democrats,9.4,13.32,11.25,22.04,?,61.95,9.11,9.297,7.400,803,12.384,3.52,12.300

In [401]:
macro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 18 columns):
Year-Month                                                           96 non-null object
Monthly Nominal GDP Index (inMillion$)                               96 non-null float64
Monthly Real GDP Index (inMillion$)                                  96 non-null float64
CPI                                                                  96 non-null float64
PartyInPower                                                         96 non-null object
unemployment rate                                                    96 non-null float64
CommercialBankInterestRateonCreditCardPlans                          96 non-null float64
Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan    96 non-null float64
Earnings or wages  in dollars per hour                               96 non-null float64
AdvertisingExpenses (in Thousand Dollars)                            96 non-null object
Cotton Monthly Price - US cents per Pound(lbs)                       96 non-null float64
Change(in%)                                                          96 non-null float64
Average upland planted(million acres)                                96 non-null float64
Average upland harvested(million acres)                              96 non-null float64
yieldperharvested acre                                               96 non-null int64
Production (in  480-lb netweright in million bales)                  96 non-null float64
Mill use  (in  480-lb netweright in million bales)                   96 non-null float64
Exports                                                              96 non-null float64
dtypes: float64(14), int64(1), object(3)
memory usage: 13.6+ KB

In [402]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
Year                         216 non-null int64
Month                        216 non-null object
ProductCategory              216 non-null object
Sales(In ThousandDollars)    216 non-null float64
Year-Month                   216 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 8.5+ KB

In [403]:
train=pd.merge(train,macro,how='inner')

In [404]:
train.head()

,Year,Month,ProductCategory,Sales(In ThousandDollars),Year-Month,Monthly Nominal GDP Index (inMillion$),Monthly Real GDP Index (inMillion$),CPI,PartyInPower,unemployment rate,...,Earnings or wages in dollars per hour,AdvertisingExpenses (in Thousand Dollars),Cotton Monthly Price - US cents per Pound(lbs),Change(in%),Average upland planted(million acres),Average upland harvested(million acres),yieldperharvested acre,Production (in 480-lb netweright in million bales),Mill use (in 480-lb netweright in million bales),Exports
0,2009,Jan,WomenClothing,1755.0,2009 - Jan,14421.752895,14407.053343,233.402,Democrats,7.8,...,22.05,137,57.70,4.02,9.296,7.559,799,12.589,4.17,11.55
1,2009,Jan,MenClothing,524.0,2009 - Jan,14421.752895,14407.053343,233.402,Democrats,7.8,...,22.05,137,57.70,4.02,9.296,7.559,799,12.589,4.17,11.55
2,2009,Jan,OtherClothing,936.0,2009 - Jan,14421.752895,14407.053343,233.402,Democrats,7.8,...,22.05,137,57.70,4.02,9.296,7.559,799,12.589,4.17,11.55
3,2009,Feb,WomenClothing,1729.0,2009 - Feb,14389.200466,14366.176571,234.663,Democrats,8.3,...,22.22,200,55.21,-4.32,9.296,7.559,799,12.589,3.87,11.10
4,2009,Feb,MenClothing,496.0,2009 - Feb,14389.200466,14366.176571,234.663,Democrats,8.3,...,22.22,200,55.21,-4.32,9.296,7.559,799,12.589,3.87,11.10

In [405]:
train['AdvertisingExpenses (in Thousand Dollars)'].value_counts()

?      186
221      3
201      3
150      3
248      3
214      3
116      3
208      3
137      3
200      3
165      3
Name: AdvertisingExpenses (in Thousand Dollars), dtype: int64

In [406]:
train['AdvertisingExpenses (in Thousand Dollars)'].replace(to_replace='?',value=221,inplace=True)

In [407]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 216 entries, 0 to 215
Data columns (total 22 columns):
Year                                                                 216 non-null int64
Month                                                                216 non-null object
ProductCategory                                                      216 non-null object
Sales(In ThousandDollars)                                            216 non-null float64
Year-Month                                                           216 non-null object
Monthly Nominal GDP Index (inMillion$)                               216 non-null float64
Monthly Real GDP Index (inMillion$)                                  216 non-null float64
CPI                                                                  216 non-null float64
PartyInPower                                                         216 non-null object
unemployment rate                                                    216 non-null float64
CommercialBankInterestRateonCreditCardPlans                          216 non-null float64
Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan    216 non-null float64
Earnings or wages  in dollars per hour                               216 non-null float64
AdvertisingExpenses (in Thousand Dollars)                            216 non-null int64
Cotton Monthly Price - US cents per Pound(lbs)                       216 non-null float64
Change(in%)                                                          216 non-null float64
Average upland planted(million acres)                                216 non-null float64
Average upland harvested(million acres)                              216 non-null float64
yieldperharvested acre                                               216 non-null int64
Production (in  480-lb netweright in million bales)                  216 non-null float64
Mill use  (in  480-lb netweright in million bales)                   216 non-null float64
Exports                                                              216 non-null float64
dtypes: float64(15), int64(3), object(4)
memory usage: 38.8+ KB

In [408]:
train.drop(['Year','Month','Year-Month','PartyInPower'],axis=1,inplace=True)

In [409]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 216 entries, 0 to 215
Data columns (total 18 columns):
ProductCategory                                                      216 non-null object
Sales(In ThousandDollars)                                            216 non-null float64
Monthly Nominal GDP Index (inMillion$)                               216 non-null float64
Monthly Real GDP Index (inMillion$)                                  216 non-null float64
CPI                                                                  216 non-null float64
unemployment rate                                                    216 non-null float64
CommercialBankInterestRateonCreditCardPlans                          216 non-null float64
Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan    216 non-null float64
Earnings or wages  in dollars per hour                               216 non-null float64
AdvertisingExpenses (in Thousand Dollars)                            216 non-null int64
Cotton Monthly Price - US cents per Pound(lbs)                       216 non-null float64
Change(in%)                                                          216 non-null float64
Average upland planted(million acres)                                216 non-null float64
Average upland harvested(million acres)                              216 non-null float64
yieldperharvested acre                                               216 non-null int64
Production (in  480-lb netweright in million bales)                  216 non-null float64
Mill use  (in  480-lb netweright in million bales)                   216 non-null float64
Exports                                                              216 non-null float64
dtypes: float64(15), int64(2), object(1)
memory usage: 32.1+ KB

In [410]:
train_dummy=pd.get_dummies(train)

In [411]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [412]:
x=train_dummy.drop('Sales(In ThousandDollars)',axis=1)

In [413]:
y=train['Sales(In ThousandDollars)']

In [414]:
train_scaled=pd.DataFrame(sc.fit_transform(x),columns=x.columns)

C:\Users\vansh\Anaconda4\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\vansh\Anaconda4\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [415]:
train_scaled

,Monthly Nominal GDP Index (inMillion$),Monthly Real GDP Index (inMillion$),CPI,unemployment rate,CommercialBankInterestRateonCreditCardPlans,"Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan",Earnings or wages in dollars per hour,AdvertisingExpenses (in Thousand Dollars),Cotton Monthly Price - US cents per Pound(lbs),Change(in%),Average upland planted(million acres),Average upland harvested(million acres),yieldperharvested acre,Production (in 480-lb netweright in million bales),Mill use (in 480-lb netweright in million bales),Exports,ProductCategory_MenClothing,ProductCategory_OtherClothing,ProductCategory_WomenClothing
0,-1.387184,-1.462736,-1.862204,-0.351845,-0.749672,1.744322,-1.538636,-4.137236,-1.085846,0.442175,-1.027054,-1.131495,0.135888,-1.041183,3.731800,0.085625,-0.707107,-0.707107,1.414214
1,-1.387184,-1.462736,-1.862204,-0.351845,-0.749672,1.744322,-1.538636,-4.137236,-1.085846,0.442175,-1.027054,-1.131495,0.135888,-1.041183,3.731800,0.085625,1.414214,-0.707107,-0.707107
2,-1.387184,-1.462736,-1.862204,-0.351845,-0.749672,1.744322,-1.538636,-4.137236,-1.085846,0.442175,-1.027054,-1.131495,0.135888,-1.041183,3.731800,0.085625,-0.707107,1.414214,-0.707107
3,-1.418525,-1.538083,-1.713338,0.048991,0.431926,0.854413,-1.325979,-0.843712,-1.154167,-0.634144,-1.027054,-1.131495,0.135888,-1.041183,1.952556,-0.166350,-0.707107,-0.707107,1.414214
4,-1.418525,-1.538083,-1.713338,0.048991,0.431926,0.854413,-1.325979,-0.843712,-1.154167,-0.634144,-1.027054,-1.131495,0.135888,-1.041183,1.952556,-0.166350,1.414214,-0.707107,-0.707107
5,-1.418525,-1.538083,-1.713338,0.048991,0.431926,0.854413,-1.325979,-0.843712,-1.154167,-0.634144,-1.027054,-1.131495,0.135888,-1.041183,1.952556,-0.166350,-0.707107,1.414214,-0.707107
6,-1.465218,-1.564607,-1.665645,0.369660,0.431926,0.854413,-1.325979,0.254130,-1.255962,-0.943876,-1.027054,-1.131495,0.135888,-1.041183,1.062934,0.141619,-0.707107,-0.707107,1.414214
7,-1.465218,-1.564607,-1.665645,0.369660,0.431926,0.854413,-1.325979,0.254130,-1.255962,-0.943876,-1.027054,-1.131495,0.135888,-1.041183,1.062934,0.141619,1.414214,-0.707107,-0.707107
8,-1.465218,-1.564607,-1.665645,0.369660,0.431926,0.854413,-1.325979,0.254130,-1.255962,-0.943876,-1.027054,-1.131495,0.135888,-1.041183,1.062934,0.141619,-0.707107,1.414214,-0.707107
9,-1.478587,-1.564948,-1.604847,0.610162,0.431926,0.854413,-1.438562,-0.111817,-1.111089,1.246187,-1.027054,-1.131495,-0.317421,-1.130272,0.469852,0.463588,-0.707107,-0.707107,1.414214
10,-1.478587,-1.564948,-1.604847,0.610162,0.431926,0.854413,-1.438562,-0.111817,-1.111089,1.246187,-1.027054,-1.131495,-0.317421,-1.130272,0.469852,0.463588,1.414214,-0.707107,-0.707107
11,-1.478587,-1.564948,-1.604847,0.610162,0.431926,0.854413,-1.438562,-0.111817,-1.111089,1.246187,-1.027054,-1.131495,-0.317421,-1.130272,0.469852,0.463588,-0.707107,1.414214,-0.707107
12,-1.460209,-1.534493,-1.558452,0.930831,0.871882,1.310777,-1.551145,0.254130,-0.969234,1.099065,-1.026473,-1.264652,0.286991,-1.137814,-0.123229,0.505584,-0.707107,-0.707107,1.414214
13,-1.460209,-1.534493,-1.558452,0.930831,0.871882,1.310777,-1.551145,0.254130,-0.969234,1.099065,-1.026473,-1.264652,0.286991,-1.137814,-0.123229,0.505584,1.414214,-0.707107,-0.707107
14,-1.460209,-1.534493,-1.558452,0.930831,0.871882,1.310777,-1.551145,0.254130,-0.969234,1.099065,-1.026473,-1.264652,0.286991,-1.137814,-0.123229,0.505584,-0.707107,1.414214,-0.707107
15,-1.457681,-1.573762,-1.417142,1.010998,0.871882,1.310777,-1.651219,0.254130,-0.984599,-0.192776,-1.392298,-0.963165,0.022561,-0.905900,-0.419770,-0.614306,-0.707107,-0.707107,1.414214
16,-1.457681,-1.573762,-1.417142,1.010998,0.871882,1.310777,-1.651219,0.254130,-0.984599,-0.192776,-1.392298,-0.963165,0.022561,-0.905900,-0.419770,-0.614306,1.414214,-0.707107,-0.707107
17,-1.457681,-1.573762,-1.417142,1.010998,0.871882,1.310777,-1.651219,0.254130,-0.984599,-0.192776,-1.392298,-0.963165,0.022561,-0.905900,-0.419770,-0.614306,-0.707107,1.414214,-0.707107
18,-1.487678,-1.575871,-1.366615,1.010998,0.871882,1.310777,-1.601182,0.254130,-0.891035,0.639629,-1.254459,-0.969027,0.022561,-0.912028,-0.419770,-0.950273,-0.707107,-0.707107,1.414214
19,-1.487678,-1.575871,-1.366615,1.010998,0.871882,1.310777,-1.601182,0.254130,-0.891035,0.639629,-1.254459,-0.969027,0.022561,-0.912028,-0.419770,-0.950273,1.414214,-0.707107,-0.707107
20,-1.487678,-1.575871,-1.366615,1.010998,0.871882,1.310777,-1.601182,0.254130,-0.891035,0.639629,-1.254459,-0.969027,0.022561,-0.912028,-0.419770,-0.950273,-0.707107,1.414214,-0.707107
21,-1.384746,-1.409725,-1.286102,1.091165,1.362119,0.489323,-1.401034,0.254130,-0.905851,-0.183742,-1.254459,-1.081247,0.513645,-0.922870,-0.419770,-0.950273,-0.707107,-0.707107,1.414214
22,-1.384746,-1.409725,-1.286102,1.091165,1.362119,0.489323,-1.401034,0.254130,-0.905851,-0.183742,-1.254459,-1.081247,0.513645,-0.922870,-0.419770,-0.950273,1.414214,-0.707107,-0.707107
23,-1.384746,-1.409725,-1.286102,1.091165,1.362119,0.489323,-1.401034,0.254130,-0.905851,-0.183742,-1.254459,-1.081247,0.513645,-0.922870,-0.419770,-0.950273,-0.707107,1.414214,-0.707107
24,-1.397751,-1.427862,-1.252339,1.251500,1.362119,0.489323,-1.350997,0.254130,-0.911065,-0.115343,-1.205605,-1.112233,1.193608,-0.813983,-0.419770,-0.782290,-0.707107,-0.707107,1.414214
25,-1.397751,-1.427862,-1.252339,1.251500,1.362119,0.489323,-1.350997,0.254130,-0.911065,-0.115343,-1.205605,-1.112233,1.193608,-0.813983,-0.419770,-0.782290,1.414214,-0.707107,-0.707107
26,-1.397751,-1.427862,-1.252339,1.251500,1.362119,0.489323,-1.350997,0.254130,-0.911065,-0.115343,-1.205605,-1.112233,1.193608,-0.813983,-0.419770,-0.782290,-0.707107,1.414214,-0.707107
27,-1.218841,-1.115574,-1.274533,1.411834,1.362119,0.489323,-1.263433,0.254130,-0.835610,0.477020,-1.205605,-1.108883,0.135888,-1.021386,-1.012851,-0.782290,-0.707107,-0.707107,1.414214
28,-1.218841,-1.115574,-1.274533,1.411834,1.362119,0.489323,-1.263433,0.254130,-0.835610,0.477020,-1.205605,-1.108883,0.135888,-1.021386,-1.012851,-0.782290,1.414214,-0.707107,-0.707107
29,-1.218841,-1.115574,-1.274533,1.411834,1.362119,0.489323,-1.263433,0.254130,-0.835610,0.477020,-1.205605,-1.108883,0.135888,-1.021386,-1.012851,-0.782290,-0.707107,1.414214,-0.707107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,1.200776,1.113175,1.274362,-1.233685,-1.001076,-1.336130,1.526126,0.254130,-0.008898,0.320863,-0.497800,-1.210217,0.438093,-1.059095,0.232620,-0.810287,-0.707107,-0.707107,1.414214
187,1.200776,1.113175,1.274362,-1.233685,-1.001076,-1.336130,1.526126,0.254130,-0.008898,0.320863,-0.497800,-1.210217,0.438093,-1.059095,0.232620,-0.810287,1.414214,-0.707107,-0.707107
188,1.200776,1.113175,1.274362,-1.233685,-1.001076,-1.336130,1.526126,0.254130,-0.008898,0.320863,-0.497800,-1.210217,0.438093,-1.059095,0.232620,-0.810287,-0.707107,1.414214,-0.707107
189,1.296175,1.234202,1.276015,-1.634521,-1.001076,-1.336130,1.401034,0.254130,-0.084353,-0.443143,-0.497800,-1.210217,-0.317421,-1.208520,0.232620,-0.796288,-0.707107,-0.707107,1.414214
190,1.296175,1.234202,1.276015,-1.634521,-1.001076,-1.336130,1.401034,0.254130,-0.084353,-0.443143,-0.497800,-1.210217,-0.317421,-1.208520,0.232620,-0.796288,1.414214,-0.707107,-0.707107
191,1.296175,1.234202,1.276015,-1.634521,-1.001076,-1.336130,1.401034,0.254130,-0.084353,-0.443143,-0.497800,-1.210217,-0.317421,-1.208520,0.232620,-0.796288,-0.707107,1.414214,-0.707107
192,1.427564,1.375329,1.422402,-1.554354,-1.001076,-2.522674,1.275942,0.254130,-0.125236,-0.280533,-0.497800,-1.310712,0.249215,-1.189193,0.232620,-0.964272,-0.707107,-0.707107,1.414214
193,1.427564,1.375329,1.422402,-1.554354,-1.001076,-2.522674,1.275942,0.254130,-0.125236,-0.280533,-0.497800,-1.310712,0.249215,-1.189193,0.232620,-0.964272,1.414214,-0.707107,-0.707107
194,1.427564,1.375329,1.422402,-1.554354,-1.001076,-2.522674,1.275942,0.254130,-0.125236,-0.280533,-0.497800,-1.310712,0.249215,-1.189193,0.232620,-0.964272,-0.707107,1.414214,-0.707107
195,1.488441,1.456869,1.437158,-1.714688,-1.001076,-2.522674,1.426053,0.254130,-0.174899,-0.328284,-0.069162,-0.264720,0.589196,-0.134740,0.796047,-1.219047,-0.707107,-0.707107,1.414214
196,1.488441,1.456869,1.437158,-1.714688,-1.001076,-2.522674,1.426053,0.254130,-0.174899,-0.328284,-0.069162,-0.264720,0.589196,-0.134740,0.796047,-1.219047,1.414214,-0.707107,-0.707107
197,1.488441,1.456869,1.437158,-1.714688,-1.001076,-2.522674,1.426053,0.254130,-0.174899,-0.328284,-0.069162,-0.264720,0.589196,-0.134740,0.796047,-1.219047,-0.707107,1.414214,-0.707107
198,1.626326,1.638471,1.454630,-1.634521,-1.001076,-2.522674,1.288451,0.254130,-0.368612,-1.079384,0.075075,-0.264720,0.324766,0.545447,1.389128,-0.939074,-0.707107,-0.707107,1.414214
199,1.626326,1.638471,1.454630,-1.634521,-1.001076,-2.522674,1.288451,0.254130,-0.368612,-1.079384,0.075075,-0.264720,0.324766,0.545447,1.389128,-0.939074,1.414214,-0.707107,-0.707107
200,1.626326,1.638471,1.454630,-1.634521,-1.001076,-2.522674,1.288451,0.254130,-0.368612,-1.079384,0.075075,-0.264720,0.324766,0.545447,1.389128,-0.939074,-0.707107,1.414214,-0.707107
201,1.754235,1.835556,1.404694,-1.634521,-1.013646,0.124232,1.300960,0.254130,-0.638604,-1.591732,0.075075,0.967189,0.475869,1.012574,1.389128,-0.698298,-0.707107,-0.707107,1.414214
202,1.754235,1.835556,1.404694,-1.634521,-1.013646,0.124232,1.300960,0.254130,-0.638604,-1.591732,0.075075,0.967189,0.475869,1.012574,1.389128,-0.698298,1.414214,-0.707107,-0.707107
203,1.754235,1.835556,1.404694,-1.634521,-1.013646,0.124232,1.300960,0.254130,-0.638604,-1.591732,0.075075,0.967189,0.475869,1.012574,1.389128,-0.698298,-0.707107,1.414214,-0.707107
204,1.701975,1.718746,1.404576,-1.875023,-1.013646,0.124232,1.526126,0.254130,-0.655615,-0.185033,-0.141862,0.654815,-0.204094,0.547803,1.389128,-1.090259,-0.707107,-0.707107,1.414214
205,1.701975,1.718746,1.404576,-1.875023,-1.013646,0.124232,1.526126,0.254130,-0.655615,-0.185033,-0.141862,0.654815,-0.204094,0.547803,1.389128,-1.090259,1.414214,-0.707107,-0.707107
206,1.701975,1.718746,1.404576,-1.875023,-1.013646,0.124232,1.526126,0.254130,-0.655615,-0.185033,-0.141862,0.654815,-0.204094,0.547803,1.389128,-1.090259,-0.707107,1.414214,-0.707107
207,1.778113,1.836282,1.336813,-2.035357,-1.013646,0.124232,1.551145,0.254130,-0.739027,-0.610914,-0.141862,0.654815,-0.732954,0.414406,1.389128,-1.090259,-0.707107,-0.707107,1.414214
208,1.778113,1.836282,1.336813,-2.035357,-1.013646,0.124232,1.551145,0.254130,-0.739027,-0.610914,-0.141862,0.654815,-0.732954,0.414406,1.389128,-1.090259,1.414214,-0.707107,-0.707107
209,1.778113,1.836282,1.336813,-2.035357,-1.013646,0.124232,1.551145,0.254130,-0.739027,-0.610914,-0.141862,0.654815,-0.732954,0.414406,1.389128,-1.090259,-0.707107,1.414214,-0.707107
210,1.831933,1.921516,1.204829,-1.955190,-0.799953,-0.469040,1.876385,0.254130,-0.816129,-0.591556,-0.141862,0.654815,-0.468524,0.481340,1.389128,-1.090259,-0.707107,-0.707107,1.414214
211,1.831933,1.921516,1.204829,-1.955190,-0.799953,-0.469040,1.876385,0.254130,-0.816129,-0.591556,-0.141862,0.654815,-0.468524,0.481340,1.389128,-1.090259,1.414214,-0.707107,-0.707107
212,1.831933,1.921516,1.204829,-1.955190,-0.799953,-0.469040,1.876385,0.254130,-0.816129,-0.591556,-0.141862,0.654815,-0.468524,0.481340,1.389128,-1.090259,-0.707107,1.414214,-0.707107
213,1.800823,1.881195,1.051123,-2.115524,-0.799953,-0.469040,1.638710,0.254130,-0.795001,0.070496,-0.141862,0.654815,-1.337365,0.257911,1.389128,-1.090259,-0.707107,-0.707107,1.414214
214,1.800823,1.881195,1.051123,-2.115524,-0.799953,-0.469040,1.638710,0.254130,-0.795001,0.070496,-0.141862,0.654815,-1.337365,0.257911,1.389128,-1.090259,1.414214,-0.707107,-0.707107
215,1.800823,1.881195,1.051123,-2.115524,-0.799953,-0.469040,1.638710,0.254130,-0.795001,0.070496,-0.141862,0.654815,-1.337365,0.257911,1.389128,-1.090259,-0.707107,1.414214,-0.707107

In [416]:
from sklearn.linear_model import LinearRegression
from sklearn.tr
LR=LinearRegression()

In [417]:
LR.fit(train_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [418]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
Year                         36 non-null int64
Month                        36 non-null object
ProductCategory              36 non-null object
Sales(In ThousandDollars)    0 non-null float64
Year-Month                   36 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 1.5+ KB

In [419]:
test.drop(['Year','Month','Sales(In ThousandDollars)'],axis=1,inplace=True)

In [420]:
test1=pd.merge(macro,test)

In [421]:
print(test_scaled.columns)
print(train_scaled.columns)
test1['AdvertisingExpenses (in Thousand Dollars)'].value_counts()

Index(['Monthly Nominal GDP Index (inMillion$)',
       'Monthly Real GDP Index (inMillion$)', 'CPI', 'unemployment rate',
       'CommercialBankInterestRateonCreditCardPlans',
       'Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan',
       'Earnings or wages  in dollars per hour',
       'Cotton Monthly Price - US cents per Pound(lbs)', 'Change(in%)',
       'Average upland planted(million acres)',
       'Average upland harvested(million acres)', 'yieldperharvested acre',
       'Production (in  480-lb netweright in million bales)',
       'Mill use  (in  480-lb netweright in million bales)', 'Exports',
       'AdvertisingExpenses (in Thousand Dollars)_183',
       'AdvertisingExpenses (in Thousand Dollars)_?',
       'ProductCategory_MenClothing', 'ProductCategory_OtherClothing',
       'ProductCategory_WomenClothing'],
      dtype='object')
Index(['Monthly Nominal GDP Index (inMillion$)',
       'Monthly Real GDP Index (inMillion$)', 'CPI', 'unemployment rate',
       'CommercialBankInterestRateonCreditCardPlans',
       'Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan',
       'Earnings or wages  in dollars per hour',
       'AdvertisingExpenses (in Thousand Dollars)',
       'Cotton Monthly Price - US cents per Pound(lbs)', 'Change(in%)',
       'Average upland planted(million acres)',
       'Average upland harvested(million acres)', 'yieldperharvested acre',
       'Production (in  480-lb netweright in million bales)',
       'Mill use  (in  480-lb netweright in million bales)', 'Exports',
       'ProductCategory_MenClothing', 'ProductCategory_OtherClothing',
       'ProductCategory_WomenClothing'],
      dtype='object')

?      33
183     3
Name: AdvertisingExpenses (in Thousand Dollars), dtype: int64

In [422]:
test1['AdvertisingExpenses (in Thousand Dollars)'].replace(to_replace='?',value=183,inplace=True)
test1.columns

Index(['Year-Month', 'Monthly Nominal GDP Index (inMillion$)',
       'Monthly Real GDP Index (inMillion$)', 'CPI', 'PartyInPower',
       'unemployment rate', 'CommercialBankInterestRateonCreditCardPlans',
       'Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan',
       'Earnings or wages  in dollars per hour',
       'AdvertisingExpenses (in Thousand Dollars)',
       'Cotton Monthly Price - US cents per Pound(lbs)', 'Change(in%)',
       'Average upland planted(million acres)',
       'Average upland harvested(million acres)', 'yieldperharvested acre',
       'Production (in  480-lb netweright in million bales)',
       'Mill use  (in  480-lb netweright in million bales)', 'Exports',
       'ProductCategory'],
      dtype='object')

In [423]:
test1.drop(['Year-Month','PartyInPower'],axis=1,inplace=True)
test1.columns

Index(['Monthly Nominal GDP Index (inMillion$)',
       'Monthly Real GDP Index (inMillion$)', 'CPI', 'unemployment rate',
       'CommercialBankInterestRateonCreditCardPlans',
       'Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan',
       'Earnings or wages  in dollars per hour',
       'AdvertisingExpenses (in Thousand Dollars)',
       'Cotton Monthly Price - US cents per Pound(lbs)', 'Change(in%)',
       'Average upland planted(million acres)',
       'Average upland harvested(million acres)', 'yieldperharvested acre',
       'Production (in  480-lb netweright in million bales)',
       'Mill use  (in  480-lb netweright in million bales)', 'Exports',
       'ProductCategory'],
      dtype='object')

In [424]:
test_dummy=pd.get_dummies(test1)
test_dummy.columns

Index(['Monthly Nominal GDP Index (inMillion$)',
       'Monthly Real GDP Index (inMillion$)', 'CPI', 'unemployment rate',
       'CommercialBankInterestRateonCreditCardPlans',
       'Finance Rate on Personal Loans at Commercial Banks, 24 Month Loan',
       'Earnings or wages  in dollars per hour',
       'AdvertisingExpenses (in Thousand Dollars)',
       'Cotton Monthly Price - US cents per Pound(lbs)', 'Change(in%)',
       'Average upland planted(million acres)',
       'Average upland harvested(million acres)', 'yieldperharvested acre',
       'Production (in  480-lb netweright in million bales)',
       'Mill use  (in  480-lb netweright in million bales)', 'Exports',
       'ProductCategory_MenClothing', 'ProductCategory_OtherClothing',
       'ProductCategory_WomenClothing'],
      dtype='object')

In [425]:
test_scaled=pd.DataFrame(sc.fit_transform(test_dummy),columns=test_dummy.columns)

C:\Users\vansh\Anaconda4\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\vansh\Anaconda4\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [426]:
print(test_scaled.shape)
print(train_scaled.shape)

(36, 19)
(216, 19)

In [427]:
predict=LR.predict(test_scaled)

In [428]:
import numpy as np

In [434]:
solution=pd.DataFrame({'S.No.':range(1,37),'Sales':predict})

In [435]:
solution.to_csv('Solution.csv',index=False)

In [432]:
predict=np.absolute(predict)

In [433]:
predict

array([1.32172585e+03, 1.18314915e+03, 7.73815815e+02, 1.59300443e+03,
       9.11870570e+02, 5.02537237e+02, 2.53570458e+03, 3.08295842e+01,
       4.40162918e+02, 2.68948581e+03, 1.84610811e+02, 5.93944144e+02,
       3.27661896e+03, 7.71743956e+02, 1.18107729e+03, 2.92029909e+03,
       4.15424086e+02, 8.24757419e+02, 3.98294902e+03, 1.47807402e+03,
       1.88740735e+03, 3.21831609e+03, 7.13441092e+02, 1.12277442e+03,
       2.50113005e+03, 3.74494971e+00, 4.05588384e+02, 3.75636731e+03,
       1.25149231e+03, 1.66082564e+03, 4.27306488e+03, 1.76818988e+03,
       2.17752321e+03, 6.34633394e+03, 3.84145894e+03, 4.25079227e+03])

In [318]:
solution=pd.DataFrame({'S.No.':range(1,37),'Sales':predict})

In [320]:
solution.to_csv('Solution1.csv',index=False)